# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_producer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14kafka_producer.proto\x12\x13kafka_producer_grpc\"\x15\n\x05Topic\x12\x0c\n\x04udid\x18\x01 \x01(\t\"*\n\x08Location\x12\x0c\n\x04udid\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\"\t\n\x07Request\")\n\x08Response\x12\x0c\n\x04udid\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x85\x02\n\x13Kafka_Producer_gRPC\x12R\n\x10\x41\x64\x64_New_Location\x12\x1d.kafka_producer_grpc.Location\x1a\x1d.kafka_producer_grpc.Response\"\x00\x12L\n\rAdd_New_Topic\x12\x1a.kafka_producer_grpc.Topic\x1a\x1d.kafka_producer_grpc.Response\"\x00\x12L\n\x0bLoad_Topics\x12\x1c.kafka_producer_grpc.Request\x1a\x1d.kafka_producer_grpc.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kafka_producer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOPIC']._serialized_start=45
  _globals['_TOPIC']._serialized_end=66
  _globals['_LOCATION']._serialized_start=68
  _globals['_LOCATION']._serialized_end=110
  _globals['_REQUEST']._serialized_start=112
  _globals['_REQUEST']._serialized_end=121
  _globals['_RESPONSE']._serialized_start=123
  _globals['_RESPONSE']._serialized_end=164
  _globals['_KAFKA_PRODUCER_GRPC']._serialized_start=167
  _globals['_KAFKA_PRODUCER_GRPC']._serialized_end=428
# @@protoc_insertion_point(module_scope)
