# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kafka_producer_pb2 as kafka__producer__pb2


class Kafka_Producer_gRPCStub(object):
    """service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add_New_Location = channel.unary_unary(
                '/kafka_producer_grpc.Kafka_Producer_gRPC/Add_New_Location',
                request_serializer=kafka__producer__pb2.Location.SerializeToString,
                response_deserializer=kafka__producer__pb2.Response.FromString,
                )
        self.Add_New_Topic = channel.unary_unary(
                '/kafka_producer_grpc.Kafka_Producer_gRPC/Add_New_Topic',
                request_serializer=kafka__producer__pb2.Topic.SerializeToString,
                response_deserializer=kafka__producer__pb2.Response.FromString,
                )


class Kafka_Producer_gRPCServicer(object):
    """service definition
    """

    def Add_New_Location(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add_New_Topic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Kafka_Producer_gRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add_New_Location': grpc.unary_unary_rpc_method_handler(
                    servicer.Add_New_Location,
                    request_deserializer=kafka__producer__pb2.Location.FromString,
                    response_serializer=kafka__producer__pb2.Response.SerializeToString,
            ),
            'Add_New_Topic': grpc.unary_unary_rpc_method_handler(
                    servicer.Add_New_Topic,
                    request_deserializer=kafka__producer__pb2.Topic.FromString,
                    response_serializer=kafka__producer__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kafka_producer_grpc.Kafka_Producer_gRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Kafka_Producer_gRPC(object):
    """service definition
    """

    @staticmethod
    def Add_New_Location(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kafka_producer_grpc.Kafka_Producer_gRPC/Add_New_Location',
            kafka__producer__pb2.Location.SerializeToString,
            kafka__producer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add_New_Topic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kafka_producer_grpc.Kafka_Producer_gRPC/Add_New_Topic',
            kafka__producer__pb2.Topic.SerializeToString,
            kafka__producer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
