apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: cloud-server
  name: cloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/csc3104-cloudcomputing-app-network: "true"
        io.kompose.service: cloud-server
    spec:
      containers:
        - image: ghcr.io/mcdulltii/cloud-server:latest
          name: cloud-server
          ports:
            - containerPort: 5001
              hostPort: 5001
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
