apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-service
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/csc3104-cloudcomputing-location-system: "true"
        io.kompose.service: consumer-service
    spec:
      containers:
        - args:
            - npm
            - start
          image: ghcr.io/mcdulltii/consumer-service:latest
          name: consumer-service
          ports:
            - containerPort: 50051
              hostPort: 50051
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
