---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: cloud-computing
  labels:
    app: consumer
spec:
  type: LoadBalancer
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30002
      name: service
  selector:
    app: consumer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: cloud-computing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      namespace: cloud-computing
      labels:
        app: consumer
    spec:
      containers:
        - args:
            - npm
            - start
          image: ghcr.io/mcdulltii/consumer-service:latest
          name: consumer-service
          ports:
            - containerPort: 50051
          resources: {}
      restartPolicy: Always
status: {}
