version: '3.8'

services:
  cloud-server:
    image: ghcr.io/mcdulltii/cloud-server:latest
    container_name: cloud-server
    restart: always
    ports:
      - 5001:5001
    networks:
      - app_network

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MARIADB_DATABASE=mysql_db
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - ./cloud/mysql-import/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      # Unqiue Broker ID
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - location-system

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - location-system

  # web-server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: web-server
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - location-system
  #   command: npm start

  consumer-service:
    image: ghcr.io/mcdulltii/consumer-service:latest
    container_name: consumer-service
    networks:
      - location-system
    ports:
      - '50051:50051'
    depends_on:
      - kafka
      - producer-service
    command: npm start

  producer-service:
    image: ghcr.io/mcdulltii/producer-service:latest
    container_name: producer-service
    networks:
      - location-system
    ports:
      - '50052:50052'
    depends_on:
      - kafka
      # - admin-service
    command: npm start

  # admin-service:
  #   build:
  #     context: ./kafka-admin
  #     dockerfile: Dockerfile
  #   container_name: admin-service
  #   networks:
  #     - location-system
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #   command: npm start

networks:
  location-system:
    driver: bridge
  app_network:
