apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-claim0-volume
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/root/Downloads/cloud/CSC3104_CloudComputing/cloud/mysql-import"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-claim0
    app: mariadb
  name: mariadb-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
