---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: cloud-computing
  labels:
    app: producer
spec:
  ports:
    - port: 50052
      targetPort: 50052
      name: service
  selector:
    app: producer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: cloud-computing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      namespace: cloud-computing
      labels:
        app: producer
    spec:
      containers:
        - args:
            - npm
            - start
          image: ghcr.io/mcdulltii/producer-service:latest
          name: producer-service
          ports:
            - containerPort: 50052
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
