---
apiVersion: v1
kind: Service
metadata:
  name: cloud-server
  namespace: cloud-computing
  labels:
    app: cloud
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
      name: server
  selector:
    app: cloud
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
  namespace: cloud-computing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      namespace: cloud-computing
      labels:
        app: cloud
    spec:
      containers:
        - image: ghcr.io/mcdulltii/cloud-server:latest
          name: cloud-server
          ports:
            - containerPort: 5001
          resources: {}
      restartPolicy: Always
status: {}
