name: flutter_app
description: Cloud Project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.1
  logging: ^1.2.0
  http: ^1.0.0
  uuid: ^4.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  grpc: ^3.2.4
  protobuf: ^3.1.0 # For Proto Files (pb files)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
